{
 "title": "Centralised AeroSpike",
 "time": { "from": "2023-02-19T11:34:28.931Z", "to": "2023-02-19T14:01:57.126Z" },
 "panels": [
  {
   "title": "Aerospike nodes up (monitoring)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time (aerospike_namespace_ns_cluster_size{service=\"aerospike-exporter\"}[1d]) - min_over_time (aerospike_namespace_ns_cluster_size{service=\"aerospike-exporter\"}[5m])",
     "legendFormat": "{{cluster}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Committee Aerospike nodes up (monitoring)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time (aerospike_namespace_ns_cluster_size{service=\"aerospike-committee-exporter\"}[1d]) - min_over_time (aerospike_namespace_ns_cluster_size{service=\"aerospike-committee-exporter\"}[5m])",
     "legendFormat": "{{cluster}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Aerospike NS memory usage (monitoring)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - avg_over_time(aerospike_namespace_memory_free_pct{service=\"aerospike-exporter\"}[1m])",
     "legendFormat": "{{cluster}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Committee Aerospike NS memory usage (monitoring)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - avg_over_time(aerospike_namespace_memory_free_pct{service=\"aerospike-committee-exporter\"}[1m])",
     "legendFormat": "{{cluster}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Aerospike MinimumContiguousDiskSpace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min_over_time(aerospike_namespace_device_available_pct{service=~\"aerospike-exporter\"}[5m])",
     "legendFormat": "{{cluster}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Committee Aerospike MinimumContiguousDiskSpace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min_over_time(aerospike_namespace_device_available_pct{service=~\"aerospike-committee-exporter\"}[5m])",
     "legendFormat": "{{cluster}} - {{instance}}"
    }
   ]
  }
 ]
}