{
 "title": "Centralaized - aviv",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "TX Time Spent In System",
   "type": "graph",
   "description": "TX Time Spent In System in hours",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (kubernetes_namespace) (starkware_time_of_tx_spent_in_system) /3600",
     "legendFormat": "{{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Transaction per second",
   "type": "graph",
   "description": "Transactions per second for 30 minutes",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (kubernetes_namespace) (rate(starkware_max_received_tx{app=\"gateway\"}[30m]))",
     "legendFormat": "{{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Transactions Processing",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "max by (kubernetes_namespace) (starkware_max_received_tx) - max by (kubernetes_namespace) (starkware_onchain_tx_offset) + 1 ",
     "legendFormat": "{{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Provers",
   "type": "graph",
   "description": "Provers",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(starkware_request_in_progress{app=\"prover\", kubernetes_namespace=\"sharp-production-v3\", funcname=\"proof_request\"}) or vector(0)",
     "legendFormat": "Sharp running provers"
    },
    {
     "expr": "sum(starkware_request_in_progress{app=\"prover\", kubernetes_namespace=\"dydx-production\", funcname=\"proof_request\"}) or vector(0)",
     "legendFormat": "dydx running provers"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 } }
 ]
}